name: 气味小站
author: Chloe
baseurl: /chloceg.github.io
description: Chloe's Site
github: http://www.github.com/chloceg
twitter: http://www.twitter.com/nanjingmengwang
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: njycgqw@163.com
location: Nanjing
disqus: Chloe

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
